### ISSUE TITLE
application has been destroyed

### ISSUE THREAD

**Issue by DevHerles** [nobotro/python-pdf-digital-signature#1]
```
 * Running on http://127.0.0.1:1327/ (Press CTRL+C to quit)
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "signature_server.py", line 15, in sig_worker
    pdfb = sm.sign_pdf(data)
  File "/home/herlesinc/asfdev/python-pdf-digital-signature/server/signature_capture.py", line 60, in sign_pdf
    self.windowloop()
  File "/home/herlesinc/asfdev/python-pdf-digital-signature/server/signature_capture.py", line 207, in windowloop
    self.master.update_idletasks()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1037, in update_idletasks
    self.tk.call('update', 'idletasks')
TclError: can't invoke "update" command: application has been destroyed
127.0.0.1 - - [16/Sep/2020 08:57:20] "GET / HTTP/1.1" 200 -
```

**Comment by nobotro** [comment]
Press right mouse button on window after draw signature to submit sign.
You can change button from here
`self.tkinter_signature_canvas.bind('<B1-Motion>', self.mouse_move)
        self.tkinter_signature_canvas.bind('<ButtonRelease-1>', self.mouse_up)
        self.tkinter_signature_canvas.bind('<ButtonPress-3>', self.sign)`
